lib/teacher_web/router.ex
defmodule TeacherWeb.Router do
  use TeacherWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TeacherWeb.Plugs.SetAuth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TeacherWeb do
    pipe_through :browser

    resources "/sessions", SessionController, only: [:new, :create]
    delete "/sign-out", SessionController, :delete
    resources "/registrations", RegistrationController, only: [:new, :create]

    resources "/cart", CartController, only: [:update, :delete]

    resources "/albums", AlbumController
    resources "/users", UserController, only: [:show]
    get "/", PageController, :index
  end
end

lib/teacher_web/views/layout_view.ex
defmodule TeacherWeb.LayoutView do
  use TeacherWeb, :view

  alias Teacher.Carts

  def cart_item_count(current_user) do
    case Carts.get(current_user.username) do
      nil ->
        0
      cart ->
        Enum.count(cart)
    end
  end
end

lib/teacher_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Teacher · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <main role="main" class="container">
      <%= link "Home", to: Routes.page_path(@conn, :index) %> |
      <%= link "Albums", to: Routes.album_path(@conn, :index) %> |
      <%= if @conn.assigns[:current_user] do %>
        <%= link "Profile", to: Routes.user_path(@conn, :show, @current_user) %> |
        <%= link "Sign out", to: Routes.session_path(@conn, :delete), method: :delete %>
        | <%= cart_item_count(@current_user) %> items(s) inn your cart
      <% else %>
        <%= link "Sign in", to: Routes.session_path(@conn, :new) %> |
        <%= link "Sign up", to: Routes.registration_path(@conn, :new) %>
      <% end %>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>